In [1]:
import numpy as np

In [2]:
A=np.array([[4,3,-5],[-2,-4,5],[8,8,0]])

In [3]:
A

array([[ 4,  3, -5],
       [-2, -4,  5],
       [ 8,  8,  0]])

In [4]:
b=np.array([2,5,-3])

In [5]:
x=np.linalg.solve(A,b)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [6]:
A_inv=np.linalg.inv(A)
x_new=np.dot(A_inv,b)
print(x_new)

[ 2.20833333 -2.58333333 -0.18333333]
