In [10]:
import numpy as np
from numpy.linalg import cond, matrix_rank

In [13]:
def Gauss_Elimination(a, y):
    if(a.shape[0] != a.shape[1]):
        print("Error\n")
    
    if(a.shape[0] != y.shape[0] or y.shape[1] > 1):
        print("Error\n")
    
    n = len(y)
    i = 0
    j = i - 1
    x = np.zeros(n)
    
    augmented_matrix = np.concatenate((a, y), axis = 1, dtype = float)
    print(f"Initial matrix : \n{augmented_matrix}\n")
    
    while i < n:
        # check it won't divide by zero
        if(augmented_matrix[i][i] == 0):
            #swap
            for k in range(1, len(augmented_matrix)):
                if augmented_matrix[k][i] != 0:
                    augmented_matrix[[i, k]] = augmented_matrix[[k, i]]    
        for j in range(i + 1, n):
            fac = augmented_matrix[j][i] / augmented_matrix[i][i]
            augmented_matrix[j] -= fac * augmented_matrix[i] 
            print(f"The new augmented matrix : \n{augmented_matrix}")
        i = i + 1
    
    # back substitution
    x[n - 1] = augmented_matrix[n - 1][n] / augmented_matrix[n - 1][n - 1]
    
    for k in range(n - 2, -1, -1):
        x[k] = augmented_matrix[k][n]
        for j in range(k + 1, n):
                x[k] = x[k] - augmented_matrix[k][j] * x[j]
        x[k] = x[k] / augmented_matrix[k][k]
            
    print(f"x: {x}")
    

In [14]:
a = np.array([[0,-2,6],[12,4,-7],[0,4,1]]).astype('float')
y = np.array([[7],[5],[3]]).astype('float')
x = Gauss_Elimination(a, y)

Initial matrix : 
[[ 0. -2.  6.  7.]
 [12.  4. -7.  5.]
 [ 0.  4.  1.  3.]]

The new augmented matrix : 
[[12.  4. -7.  5.]
 [ 0. -2.  6.  7.]
 [ 0.  4.  1.  3.]]
The new augmented matrix : 
[[12.  4. -7.  5.]
 [ 0. -2.  6.  7.]
 [ 0.  4.  1.  3.]]
The new augmented matrix : 
[[12.  4. -7.  5.]
 [ 0. -2.  6.  7.]
 [ 0.  0. 13. 17.]]
x: [1.03846154 0.42307692 1.30769231]
