In [10]:
import numpy as np

def gauss_elimination(A, b):
    """Solves the system of linear equations Ax=b using Gauss elimination."""
    
    n = len(A)
    for i in range(n):
        # Find the pivot row and swap it with the current row
        pivot_row = i
        for j in range(i+1, n):
            if abs(A[j,i]) > abs(A[pivot_row,i]):
                pivot_row = j
        A[[i,pivot_row]] = A[[pivot_row,i]]
        b[[i,pivot_row]] = b[[pivot_row,i]]
        print(A)
        print(b)
        
        # Eliminate the current column
        for j in range(i+1, n):
            factor = A[j,i] / A[i,i]
            A[j,i:] = A[j,i:] - factor * A[i,i:]
            b[j] = b[j] - factor * b[i]
    
    # Solve the upper triangular system using back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i,i+1:], x[i+1:])) / A[i,i]
    
    return x


In [25]:
A = np.array([[1, 4, 3],
              [4, 6, 7],
              [4, 8, 9]])

b = np.array([1, 2, 3])

#x = gauss_elimination(A, b)

#print(x)


In [18]:
A

array([[1, 4, 3],
       [4, 6, 7],
       [4, 8, 9]])

In [19]:
b

array([1, 2, 3])

In [20]:
x = gauss_elimination(A, b)

[[4 6 7]
 [1 4 3]
 [4 8 9]]
[2 1 3]
[[4 6 7]
 [0 2 1]
 [0 2 2]]
[2 0 1]
[[4 6 7]
 [0 2 1]
 [0 0 1]]
[2 0 1]


In [22]:
print(x)

[-0.5 -0.5  1. ]


In [30]:
print(np.linalg.solve(A,b))

[-0.4 -0.1  0.6]
